"""sub-scores de rentabilidad, salud financiera y volumen

Revision ID: 654ba862e5f5
Revises: e9ea48cae940
Create Date: 2026-09-16 08:33:08.217903
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "654ba862e5f5"
down_revision: str | None = "e9ea48cae940"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "score", sa.Column("profitability", sa.Numeric(precision=6, scale=2), nullable=True)
    )
    op.add_column(
        "score", sa.Column("financial_health", sa.Numeric(precision=6, scale=2), nullable=True)
    )
    op.add_column("score", sa.Column("volume", sa.Numeric(precision=6, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("score", "volume")
    op.drop_column("score", "financial_health")
    op.drop_column("score", "profitability")
    # ### end Alembic commands ###
