"""activo y pasivo corriente y gastos financieros

Revision ID: 478a967bccd7
Revises: 654ba862e5f5
Create Date: 2026-09-16 08:39:58.513043
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "478a967bccd7"
down_revision: str | None = "654ba862e5f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fundamental_snapshot",
        sa.Column("current_assets", sa.Numeric(precision=24, scale=4), nullable=True),
    )
    op.add_column(
        "fundamental_snapshot",
        sa.Column("current_liabilities", sa.Numeric(precision=24, scale=4), nullable=True),
    )
    op.add_column(
        "fundamental_snapshot",
        sa.Column("interest_expense", sa.Numeric(precision=24, scale=4), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fundamental_snapshot", "interest_expense")
    op.drop_column("fundamental_snapshot", "current_liabilities")
    op.drop_column("fundamental_snapshot", "current_assets")
    # ### end Alembic commands ###
