"""esquema inicial

Las 29 tablas de la FASE 2, mas las particiones anuales de `price`.

Las particiones se crean aqui con SQL explicito porque SQLAlchemy declara la
tabla como particionada pero no crea las particiones, y una tabla particionada
sin particiones rechaza todos los INSERT. Se cubren 2000-2035 y NO se crea una
particion por defecto: una fecha fuera de ese rango es casi siempre un error de
mapeo del proveedor, y es mejor que falle al cargar que se acumule en un cajon
de sastre donde nadie la mira. Anadir anos es una migracion de una linea.

Revision ID: e9ea48cae940
Revises:
Create Date: 2026-09-15 19:24:00.181106
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e9ea48cae940"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: Rango de particiones de `price`. Ampliarlo es una migracion nueva con un
#: CREATE TABLE ... PARTITION OF por cada ano que se anada.
PRIMER_ANIO = 2000
ULTIMO_ANIO = 2035


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "country",
        sa.Column("code", sa.String(length=2), nullable=False, comment="ISO 3166-1 alfa-2"),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_country")),
    )
    op.create_table(
        "currency",
        sa.Column("code", sa.String(length=3), nullable=False, comment="ISO 4217"),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("minor_units", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_currency")),
    )
    op.create_table(
        "feature_snapshot",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("feature_set_version", sa.String(length=32), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False, comment="sha256"),
        sa.Column("row_count", sa.BigInteger(), nullable=True),
        sa.Column("feature_names", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_snapshot")),
        sa.UniqueConstraint(
            "feature_set_version",
            "as_of_date",
            name="uq_feature_snapshot_feature_set_version_as_of_date",
        ),
    )
    op.create_table(
        "fx_rate",
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("quote_currency", sa.String(length=3), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.CheckConstraint("rate > 0", name=op.f("ck_fx_rate_tasa_positiva")),
        sa.PrimaryKeyConstraint("base_currency", "quote_currency", "date", name=op.f("pk_fx_rate")),
    )
    op.create_index("ix_fx_rate_date", "fx_rate", ["date"], unique=False)
    op.create_table(
        "model_version",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("training_date", sa.Date(), nullable=True),
        sa.Column("training_period_start", sa.Date(), nullable=True),
        sa.Column("training_period_end", sa.Date(), nullable=True),
        sa.Column("benchmark_symbol", sa.String(length=32), nullable=True),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('rules', 'statistical')", name=op.f("ck_model_version_kind_valido")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_version")),
        sa.UniqueConstraint("name", "version", name="uq_model_version_name_version"),
    )
    op.create_table(
        "user_account",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("auth_provider", sa.String(length=32), nullable=True),
        sa.Column("subscription_plan", sa.String(length=16), nullable=False),
        sa.Column("risk_profile", sa.String(length=16), nullable=True),
        sa.Column("investment_horizon", sa.String(length=16), nullable=True),
        sa.Column("preferred_markets", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "investment_horizon IN ('short', 'medium', 'long')",
            name=op.f("ck_user_account_investment_horizon_valido"),
        ),
        sa.CheckConstraint(
            "risk_profile IN ('conservative', 'moderate', 'aggressive')",
            name=op.f("ck_user_account_risk_profile_valido"),
        ),
        sa.CheckConstraint(
            "subscription_plan IN ('free', 'pro', 'premium')",
            name=op.f("ck_user_account_subscription_plan_valido"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_account")),
    )
    op.create_index(
        "uq_user_account_email_lower",
        "user_account",
        [sa.literal_column("lower(email)")],
        unique=True,
    )
    op.create_table(
        "market",
        sa.Column("id", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "trading_calendar",
            sa.String(length=16),
            nullable=False,
            comment="codigo de exchange_calendars, p. ej. XMAD",
        ),
        sa.Column("classification", sa.String(length=16), nullable=False),
        sa.Column("ticker_suffix", sa.String(length=8), nullable=False),
        sa.Column("benchmark_symbol", sa.String(length=32), nullable=True),
        sa.Column("benchmark_is_total_return", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "classification IN ('developed', 'emerging')",
            name=op.f("ck_market_classification_valida"),
        ),
        sa.ForeignKeyConstraint(
            ["country_code"], ["country.code"], name=op.f("fk_market_country_code_country")
        ),
        sa.ForeignKeyConstraint(
            ["currency_code"], ["currency.code"], name=op.f("fk_market_currency_code_currency")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market")),
    )
    op.create_table(
        "portfolio",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["base_currency"], ["currency.code"], name=op.f("fk_portfolio_base_currency_currency")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_portfolio_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio")),
        sa.UniqueConstraint("user_id", "name", name="uq_portfolio_user_id_name"),
    )
    op.create_table(
        "saved_screener",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_saved_screener_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_screener")),
        sa.UniqueConstraint("user_id", "name", name="uq_saved_screener_user_id_name"),
    )
    op.create_table(
        "watchlist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_watchlist_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist")),
        sa.UniqueConstraint("user_id", "name", name="uq_watchlist_user_id_name"),
    )
    op.create_table(
        "data_freshness",
        sa.Column("dataset", sa.String(length=32), nullable=False),
        sa.Column("market_id", sa.String(length=8), nullable=False),
        sa.Column("last_data_date", sa.Date(), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=True),
        sa.Column("securities_covered", sa.Integer(), nullable=True),
        sa.Column("securities_expected", sa.Integer(), nullable=True),
        sa.Column("is_stale", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["market_id"], ["market.id"], name=op.f("fk_data_freshness_market_id_market")
        ),
        sa.PrimaryKeyConstraint("dataset", "market_id", name=op.f("pk_data_freshness")),
    )
    op.create_table(
        "exchange",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("mic", sa.String(length=4), nullable=True, comment="ISO 10383"),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("market_id", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_code"], ["country.code"], name=op.f("fk_exchange_country_code_country")
        ),
        sa.ForeignKeyConstraint(
            ["market_id"], ["market.id"], name=op.f("fk_exchange_market_id_market")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exchange")),
        sa.UniqueConstraint("code", name=op.f("uq_exchange_code")),
    )
    op.create_table(
        "pipeline_run",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("pipeline", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column(
            "run_date", sa.Date(), nullable=False, comment="dia logico, no el instante de ejecucion"
        ),
        sa.Column(
            "market_id",
            sa.String(length=8),
            nullable=True,
            comment="cada mercado se procesa tras SU cierre; no hay cierre global",
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rows_affected", sa.BigInteger(), nullable=True),
        sa.Column("snapshot_downloaded_at", sa.Date(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed', 'skipped')",
            name=op.f("ck_pipeline_run_status_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["market_id"], ["market.id"], name=op.f("fk_pipeline_run_market_id_market")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_run")),
        sa.UniqueConstraint(
            "pipeline",
            "stage",
            "run_date",
            "market_id",
            name="uq_pipeline_run_pipeline_stage_run_date_market_id",
        ),
    )
    op.create_index(
        "ix_pipeline_run_run_date_status", "pipeline_run", ["run_date", "status"], unique=False
    )
    op.create_table(
        "data_quality_check",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("dataset", sa.String(length=32), nullable=False),
        sa.Column("market_id", sa.String(length=8), nullable=True),
        sa.Column("check_name", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IN ('info', 'warning', 'critical')",
            name=op.f("ck_data_quality_check_severity_valida"),
        ),
        sa.CheckConstraint(
            "status IN ('passed', 'warning', 'failed')",
            name=op.f("ck_data_quality_check_status_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["market_id"], ["market.id"], name=op.f("fk_data_quality_check_market_id_market")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_run.id"],
            name=op.f("fk_data_quality_check_run_id_pipeline_run"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_quality_check")),
    )
    op.create_index(
        "ix_data_quality_check_source_dataset_checked_at",
        "data_quality_check",
        ["source", "dataset", "checked_at"],
        unique=False,
    )
    op.create_table(
        "security",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "ticker",
            sa.String(length=32),
            nullable=False,
            comment="simbolo canonico del motor, p. ej. ITX.MC",
        ),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column(
            "company_id",
            sa.String(length=32),
            nullable=True,
            comment="agrupa las lineas de cotizacion de una misma empresa (ADR + local)",
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("market_id", sa.String(length=8), nullable=False),
        sa.Column("exchange_id", sa.Integer(), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("asset_type", sa.String(length=16), nullable=False),
        sa.Column("sector", sa.String(length=64), nullable=True),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("listed_from", sa.Date(), nullable=True),
        sa.Column("listed_to", sa.Date(), nullable=True),
        sa.Column("is_primary_listing", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "asset_type IN ('common_stock', 'adr', 'etf', 'reit', 'index', 'fund')",
            name=op.f("ck_security_asset_type_valido"),
        ),
        sa.CheckConstraint(
            "listed_to IS NULL OR listed_from IS NULL OR listed_to >= listed_from",
            name=op.f("ck_security_alta_antes_que_baja"),
        ),
        sa.ForeignKeyConstraint(
            ["currency_code"], ["currency.code"], name=op.f("fk_security_currency_code_currency")
        ),
        sa.ForeignKeyConstraint(
            ["exchange_id"], ["exchange.id"], name=op.f("fk_security_exchange_id_exchange")
        ),
        sa.ForeignKeyConstraint(
            ["market_id"], ["market.id"], name=op.f("fk_security_market_id_market")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security")),
        sa.UniqueConstraint("market_id", "ticker", name="uq_security_market_id_ticker"),
    )
    op.create_index("ix_security_company_id", "security", ["company_id"], unique=False)
    op.create_index("ix_security_isin", "security", ["isin"], unique=False)
    op.create_index(
        "ix_security_market_id_active", "security", ["market_id", "active"], unique=False
    )
    op.create_table(
        "alert",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "security_id",
            sa.Integer(),
            nullable=True,
            comment="nulo = la alerta aplica a toda la cartera o watchlist",
        ),
        sa.Column("alert_type", sa.String(length=48), nullable=False),
        sa.Column("threshold", sa.Numeric(precision=16, scale=6), nullable=True),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "alert_type IN ('score_crosses_threshold', 'score_changes_by', 'signal_changes', 'price_moves_by', 'volatility_increases', 'fundamental_deterioration', 'technical_deterioration', 'earnings_approaching')",
            name=op.f("ck_alert_alert_type_valido"),
        ),
        sa.CheckConstraint(
            "channel IN ('email', 'push', 'telegram', 'whatsapp')",
            name=op.f("ck_alert_channel_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
            name=op.f("fk_alert_security_id_security"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_alert_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert")),
    )
    op.create_table(
        "corporate_action",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("action_type", sa.String(length=24), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("ratio", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("amount", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action_type IN ('split', 'dividend', 'ticker_change', 'merger', 'delisting')",
            name=op.f("ck_corporate_action_action_type_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
            name=op.f("fk_corporate_action_security_id_security"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corporate_action")),
        sa.UniqueConstraint(
            "security_id",
            "action_type",
            "effective_date",
            name="uq_corporate_action_security_id_action_type_effective_date",
        ),
    )
    op.create_table(
        "explanation",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("score_hash", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("positives", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("negatives", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("recent_changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("questions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("llm_model", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
            name=op.f("fk_explanation_security_id_security"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_explanation")),
        sa.UniqueConstraint(
            "security_id",
            "date",
            "score_hash",
            "language",
            name="uq_explanation_security_id_date_score_hash_language",
        ),
    )
    op.create_table(
        "fundamental_snapshot",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("period", sa.String(length=16), nullable=False),
        sa.Column("publication_date", sa.Date(), nullable=False),
        sa.Column(
            "publication_date_origin",
            sa.String(length=32),
            nullable=False,
            comment="real | estimada_retraso",
        ),
        sa.Column("pit_origin", sa.String(length=16), nullable=False),
        sa.Column("revenue", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("gross_profit", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("operating_income", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("ebit", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("ebitda", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("net_income", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("eps", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("free_cash_flow", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("total_assets", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("total_debt", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("net_debt", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("cash", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("equity", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("shares_outstanding", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("enterprise_value", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("roe", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("roa", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("gross_margin", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("operating_margin", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("net_margin", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("reporting_currency", sa.String(length=3), nullable=True),
        sa.Column("listing_currency", sa.String(length=3), nullable=True),
        sa.Column(
            "extra",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="campos del proveedor que aun no tienen columna propia",
        ),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("downloaded_at", sa.Date(), nullable=False),
        sa.CheckConstraint(
            "period IN ('annual', 'quarterly', 'semiannual')",
            name=op.f("ck_fundamental_snapshot_period_valido"),
        ),
        sa.CheckConstraint(
            "pit_origin IN ('captured', 'reconstructed')",
            name=op.f("ck_fundamental_snapshot_pit_origin_valido"),
        ),
        sa.CheckConstraint(
            "publication_date >= period_end",
            name=op.f("ck_fundamental_snapshot_publicacion_tras_el_periodo"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
            name=op.f("fk_fundamental_snapshot_security_id_security"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fundamental_snapshot")),
        sa.UniqueConstraint(
            "security_id",
            "period_end",
            "period",
            name="uq_fundamental_snapshot_security_id_period_end_period",
        ),
    )
    op.create_index(
        "ix_fundamental_snapshot_security_id_publication_date",
        "fundamental_snapshot",
        ["security_id", "publication_date"],
        unique=False,
    )
    op.create_table(
        "index_composition",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("index_code", sa.String(length=32), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from",
            name=op.f("ck_index_composition_rango_coherente"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
            name=op.f("fk_index_composition_security_id_security"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_index_composition")),
        sa.UniqueConstraint(
            "index_code",
            "security_id",
            "valid_from",
            name="uq_index_composition_index_code_security_id_valid_from",
        ),
    )
    op.create_index(
        "ix_index_composition_index_code_valid_from",
        "index_composition",
        ["index_code", "valid_from"],
        unique=False,
    )
    op.create_table(
        "model_prediction",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=False),
        sa.Column("prediction_date", sa.Date(), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("probability", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("expected_return", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("benchmark_symbol", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("horizon_days > 0", name=op.f("ck_model_prediction_horizonte_positivo")),
        sa.CheckConstraint(
            "probability IS NULL OR probability BETWEEN 0 AND 1",
            name=op.f("ck_model_prediction_probabilidad_en_rango"),
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_version.id"],
            name=op.f("fk_model_prediction_model_version_id_model_version"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
            name=op.f("fk_model_prediction_security_id_security"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_prediction")),
        sa.UniqueConstraint(
            "security_id",
            "model_version_id",
            "prediction_date",
            "horizon_days",
            name="uq_model_prediction_valor_modelo_fecha_horizonte",
        ),
    )
    op.create_table(
        "portfolio_position",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("average_price", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("target_weight", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolio.id"],
            name=op.f("fk_portfolio_position_portfolio_id_portfolio"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
            name=op.f("fk_portfolio_position_security_id_security"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_position")),
        sa.UniqueConstraint(
            "portfolio_id", "security_id", name="uq_portfolio_position_portfolio_id_security_id"
        ),
    )
    op.create_table(
        "portfolio_transaction",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("transaction_type", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("fees", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("taxes", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("fx_rate_to_base", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("executed_on", sa.Date(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "transaction_type IN ('buy', 'sell', 'dividend', 'fee')",
            name=op.f("ck_portfolio_transaction_transaction_type_valido"),
        ),
        sa.CheckConstraint(
            "fees >= 0", name=op.f("ck_portfolio_transaction_comisiones_no_negativas")
        ),
        sa.CheckConstraint("price >= 0", name=op.f("ck_portfolio_transaction_precio_no_negativo")),
        sa.CheckConstraint(
            "quantity >= 0", name=op.f("ck_portfolio_transaction_cantidad_no_negativa")
        ),
        sa.ForeignKeyConstraint(
            ["currency_code"],
            ["currency.code"],
            name=op.f("fk_portfolio_transaction_currency_code_currency"),
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolio.id"],
            name=op.f("fk_portfolio_transaction_portfolio_id_portfolio"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
            name=op.f("fk_portfolio_transaction_security_id_security"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_transaction")),
    )
    op.create_index(
        "ix_portfolio_transaction_portfolio_id_executed_on",
        "portfolio_transaction",
        ["portfolio_id", "executed_on"],
        unique=False,
    )
    op.create_table(
        "price",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("high", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("low", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("close", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column(
            "close_raw", sa.Numeric(precision=20, scale=6), nullable=True, comment="sin ajustar"
        ),
        sa.Column("volume", sa.BigInteger(), nullable=True, comment="sin ajustar"),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("downloaded_at", sa.Date(), nullable=False),
        sa.CheckConstraint("close >= 0", name=op.f("ck_price_cierre_no_negativo")),
        sa.CheckConstraint(
            "high IS NULL OR low IS NULL OR high >= low", name=op.f("ck_price_ohlc_coherente")
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
            name=op.f("fk_price_security_id_security"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("security_id", "date", name=op.f("pk_price")),
        postgresql_partition_by="RANGE (date)",
    )
    op.create_index("ix_price_date", "price", ["date"], unique=False)
    op.create_table(
        "score",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=False),
        sa.Column("overall", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("fundamental", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("technical", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("sentiment", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "risk", sa.Numeric(precision=6, scale=2), nullable=True, comment="100 = menor riesgo"
        ),
        sa.Column("growth", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("quality", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("valuation", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("momentum", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("trend", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("volatility", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("cohort_used", sa.String(length=24), nullable=False),
        sa.Column("n_cohort", sa.Integer(), nullable=False),
        sa.Column("available_pillars", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("feature_snapshot_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cohort_used IN ('market_sector', 'market', 'block', 'insufficient')",
            name=op.f("ck_score_cohort_used_valido"),
        ),
        sa.CheckConstraint("n_cohort >= 0", name=op.f("ck_score_n_cohort_no_negativo")),
        sa.CheckConstraint("overall BETWEEN 0 AND 100", name=op.f("ck_score_overall_en_rango")),
        sa.ForeignKeyConstraint(
            ["feature_snapshot_id"],
            ["feature_snapshot.id"],
            name=op.f("fk_score_feature_snapshot_id_feature_snapshot"),
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_version.id"],
            name=op.f("fk_score_model_version_id_model_version"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
            name=op.f("fk_score_security_id_security"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_score")),
        sa.UniqueConstraint(
            "security_id",
            "date",
            "model_version_id",
            name="uq_score_security_id_date_model_version_id",
        ),
    )
    op.create_index(
        "ix_score_date_model_version_id_overall",
        "score",
        ["date", "model_version_id", "overall"],
        unique=False,
    )
    op.create_index("ix_score_security_id_date", "score", ["security_id", "date"], unique=False)
    op.create_table(
        "signal",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=False),
        sa.Column("signal", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("horizon_days", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("reason_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("market_regime", sa.String(length=24), nullable=True),
        sa.Column(
            "produced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("author", sa.String(length=120), nullable=False),
        sa.Column("methodology_ref", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "signal IN ('strong_buy', 'buy', 'hold', 'sell', 'strong_sell')",
            name=op.f("ck_signal_signal_valida"),
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_version.id"],
            name=op.f("fk_signal_model_version_id_model_version"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
            name=op.f("fk_signal_security_id_security"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal")),
        sa.UniqueConstraint(
            "security_id",
            "date",
            "model_version_id",
            name="uq_signal_security_id_date_model_version_id",
        ),
    )
    op.create_index("ix_signal_date_signal", "signal", ["date", "signal"], unique=False)
    op.create_table(
        "technical_indicator",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("sma_20", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("sma_50", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("sma_100", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("sma_200", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("ema_20", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("rsi_14", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("macd", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("macd_signal", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("atr_14", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("adx_14", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("stochastic_k", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("bollinger_position", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("volatility_annualized", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("beta", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("max_drawdown_1y", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("momentum_12_1", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("relative_strength", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("distance_from_52w_high", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("distance_from_52w_low", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("volume_ratio_20", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
            name=op.f("fk_technical_indicator_security_id_security"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("security_id", "date", name=op.f("pk_technical_indicator")),
    )
    op.create_index("ix_technical_indicator_date", "technical_indicator", ["date"], unique=False)
    op.create_table(
        "watchlist_item",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("watchlist_id", sa.Integer(), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["security_id"], ["security.id"], name=op.f("fk_watchlist_item_security_id_security")
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["watchlist.id"],
            name=op.f("fk_watchlist_item_watchlist_id_watchlist"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist_item")),
        sa.UniqueConstraint(
            "watchlist_id", "security_id", name="uq_watchlist_item_watchlist_id_security_id"
        ),
    )
    op.create_table(
        "alert_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("alert_id", sa.Integer(), nullable=False),
        sa.Column("triggered_on", sa.Date(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alert.id"],
            name=op.f("fk_alert_event_alert_id_alert"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_event")),
        sa.UniqueConstraint("alert_id", "dedupe_key", name="uq_alert_event_alert_id_dedupe_key"),
    )
    # ### end Alembic commands ###

    for anio in range(PRIMER_ANIO, ULTIMO_ANIO + 1):
        op.execute(
            f"CREATE TABLE price_p{anio} PARTITION OF price "
            f"FOR VALUES FROM ('{anio}-01-01') TO ('{anio + 1}-01-01')"
        )


def downgrade() -> None:
    for anio in range(PRIMER_ANIO, ULTIMO_ANIO + 1):
        op.execute(f"DROP TABLE IF EXISTS price_p{anio}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alert_event")
    op.drop_table("watchlist_item")
    op.drop_index("ix_technical_indicator_date", table_name="technical_indicator")
    op.drop_table("technical_indicator")
    op.drop_index("ix_signal_date_signal", table_name="signal")
    op.drop_table("signal")
    op.drop_index("ix_score_security_id_date", table_name="score")
    op.drop_index("ix_score_date_model_version_id_overall", table_name="score")
    op.drop_table("score")
    op.drop_index("ix_price_date", table_name="price")
    op.drop_table("price")
    op.drop_index(
        "ix_portfolio_transaction_portfolio_id_executed_on", table_name="portfolio_transaction"
    )
    op.drop_table("portfolio_transaction")
    op.drop_table("portfolio_position")
    op.drop_table("model_prediction")
    op.drop_index("ix_index_composition_index_code_valid_from", table_name="index_composition")
    op.drop_table("index_composition")
    op.drop_index(
        "ix_fundamental_snapshot_security_id_publication_date", table_name="fundamental_snapshot"
    )
    op.drop_table("fundamental_snapshot")
    op.drop_table("explanation")
    op.drop_table("corporate_action")
    op.drop_table("alert")
    op.drop_index("ix_security_market_id_active", table_name="security")
    op.drop_index("ix_security_isin", table_name="security")
    op.drop_index("ix_security_company_id", table_name="security")
    op.drop_table("security")
    op.drop_index(
        "ix_data_quality_check_source_dataset_checked_at", table_name="data_quality_check"
    )
    op.drop_table("data_quality_check")
    op.drop_index("ix_pipeline_run_run_date_status", table_name="pipeline_run")
    op.drop_table("pipeline_run")
    op.drop_table("exchange")
    op.drop_table("data_freshness")
    op.drop_table("watchlist")
    op.drop_table("saved_screener")
    op.drop_table("portfolio")
    op.drop_table("market")
    op.drop_index("uq_user_account_email_lower", table_name="user_account")
    op.drop_table("user_account")
    op.drop_table("model_version")
    op.drop_index("ix_fx_rate_date", table_name="fx_rate")
    op.drop_table("fx_rate")
    op.drop_table("feature_snapshot")
    op.drop_table("currency")
    op.drop_table("country")
    # ### end Alembic commands ###
